channels:
- conda-forge
- defaults
dependencies:
- python=3.12.7
- pip<=25.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.3.0
  - scikit-learn==1.7.0
  - google-api-python-client
  - google-auth
  - google-auth-oauthlib 
  - google-auth-httplib2
  - docker
name: mlflow-env
